index:
    path: /
    controller: App\Controller\STController::index

figure:
       path: /figure/{nomFigure}
       controller: App\Controller\STController::afficherFigure  

show_more_comments:
       path: /afficher-plus-de-commentaires
       controller: App\Controller\STController::afficherPlusCommentaires  
       
app_login:
    path: /connexion
    controller: App\Controller\STController::login 
    
forgotten_password:
    path: /mot-de-passe-oublie
    controller: App\Controller\UserController::motDePasseOublie

reset_password:
    path: /reinitialiser-mon-mot-de-passe/{resetPasswordToken}
    controller: App\Controller\UserController::reinitialiserMotDePasse    
    requirements:
        resetPasswordToken: '\w+'
        
signup:
    path: /inscription
    controller: App\Controller\UserController::signup
    
app_logout:
    path: /deconnexion
    controller: App\Controller\STController::deconnexion
    
add_trick:
    path: /ajouter-une-figure
    controller: App\Controller\STController::ajoutFigure
 

update_trick:
    path: /modifier-une-figure/{idFigure}
    controller: App\Controller\STController::modifierFigure
    requirements:
        idFigure: '\d+'
        
delete_trick:
    path: /supprimer-une-figure/{idFigure}
    controller: App\Controller\STController::supprimerFigure
    requirements:
        idFigure: '\d+'

add_media:
    path: /ajouter-un-media/{idFigure}
    controller: App\Controller\STController::ajoutMedia
    requirements:
        idFigure: '\d+'

update_media:
    path: /modifier-un-media/{idMedia}/{idFigure}
    controller: App\Controller\STController::modifierMedia
    requirements:
        idMedia: '\d+'
        idFigure: '\d+'
        
delete_media:
    path: /supprimer-un-media/{idMedia}/{idFigure}
    controller: App\Controller\STController::supprimerMedia
    requirements:
        idMedia: '\d+'
        idFigure: '\d+'
        
profil_membre:
    path: /profil-membre/{idUtilisateur}
    controller: App\Controller\STController::AfficherProfilMembre
    requirements:
        idUtilisateur: '\d+'

activer_compte:
    path: /activer-mon-compte/{token}
    controller: App\Controller\UserController::ActiverCompte
    requirements:
        token: '\w+'