index:
    path: /
    controller: App\Controller\STController::index

figure:
       path: /figure/{nomFigure}
       controller: App\Controller\STController::afficherFigure  
       
app_login:
    path: /connexion
    controller: App\Controller\STController::login   
    
signup:
    path: /inscription
    controller: App\Controller\STController::signup
    
app_logout:
    path: /deconnexion
    controller: App\Controller\STController::deconnexion
    
dashboard:
    path: /tableau-de-bord
    controller: App\Controller\STController::dashboard
    
add_trick:
    path: /ajouter-une-figure
    controller: App\Controller\STController::ajoutFigure
 

update_trick:
    path: /modifier-une-figure/{idFigure}
    controller: App\Controller\STController::modifierFigure
    requirements:
        idFigure: '\d+'
        
delete_trick:
    path: /supprimer-une-figure/{idFigure}
    controller: App\Controller\STController::supprimerFigure
    requirements:
        idFigure: '\d+'